import React, { useState, useMemo, useEffect } from 'react';
import {
  X,
  Download,
  Filter,
  CheckSquare,
  Square,
  Layers,
  Tag,
  Briefcase,
  Search,
  CheckCircle2,
  FileSpreadsheet,
  Sliders,
  AlertCircle,
  Sparkles,
  Info,
  Calendar,
} from 'lucide-react';
import { ExportFilterMode, ExportFilterOptions, StockListItem, TokopediaRowMatch } from '../types';
import { generateTokopediaFilename } from '../lib/tokopediaProcessor';

interface TokopediaDownloadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirmDownload: (options: ExportFilterOptions, dateFormat?: 'dash' | 'readable') => void;
  matches: TokopediaRowMatch[];
  stockList?: StockListItem[];
  initialPrefix?: string;
  defaultPrefix?: string;
  stockSheetName?: string;
  isProcessing?: boolean;
}

export const TokopediaDownloadModal: React.FC<TokopediaDownloadModalProps> = ({
  isOpen,
  onClose,
  onConfirmDownload,
  matches,
  stockList,
  initialPrefix,
  defaultPrefix = 'tokopedia',
  stockSheetName = 'STOCK LIST',
  isProcessing = false,
}) => {
  const [mode, setMode] = useState<ExportFilterMode>('all');
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
  const [selectedBrands, setSelectedBrands] = useState<string[]>([]);
  const [selectedRowIndices, setSelectedRowIndices] = useState<Set<number>>(new Set());
  const [dateFormat, setDateFormat] = useState<'dash' | 'readable'>('dash');

  const effectiveBase = (initialPrefix || defaultPrefix || 'tokopedia').trim();

  // Auto-calculated prefix based on selected mode & filter (e.g. DELI-tokopedia)
  const autoGeneratedPrefix = useMemo(() => {
    const base = effectiveBase;
    if (mode === 'brand' && selectedBrands.length > 0) {
      const cleanBrands = selectedBrands
        .map((b) => b.trim().replace(/[^a-zA-Z0-9_-]/g, '_'))
        .filter(Boolean);
      if (cleanBrands.length > 0) {
        const brandTag = cleanBrands.slice(0, 3).join('_');
        return `${brandTag}-${base}`;
      }
    } else if (mode === 'category' && selectedCategories.length > 0) {
      const cleanCats = selectedCategories
        .map((c) => c.trim().replace(/[^a-zA-Z0-9_-]/g, '_'))
        .filter(Boolean);
      if (cleanCats.length > 0) {
        const catTag = cleanCats.slice(0, 2).join('_');
        return `${catTag}-${base}`;
      }
    }
    return base;
  }, [mode, selectedBrands, selectedCategories, effectiveBase]);

  const [customPrefix, setCustomPrefix] = useState<string>(autoGeneratedPrefix);

  // Search queries within modal tabs
  const [categorySearch, setCategorySearch] = useState('');
  const [brandSearch, setBrandSearch] = useState('');
  const [itemSearch, setItemSearch] = useState('');
  const [itemStockFilter, setItemStockFilter] = useState<'all' | 'in_stock' | 'out_of_stock'>('all');
  const [showItemPreview, setShowItemPreview] = useState(true);

  // Reset & initialize state when modal opens
  useEffect(() => {
    if (isOpen) {
      setCustomPrefix(autoGeneratedPrefix);
      setSelectedRowIndices(new Set(matches.map((m) => m.rowIndex)));
    }
  }, [isOpen, autoGeneratedPrefix, matches]);

  // Keep prefix automatically updated when user checks/unchecks brands or categories
  useEffect(() => {
    setCustomPrefix(autoGeneratedPrefix);
  }, [autoGeneratedPrefix]);

  // Extract unique Categories from matched items with count
  const categoryStats = useMemo(() => {
    const map = new Map<string, { count: number; inStockCount: number; items: TokopediaRowMatch[] }>();
    for (const match of matches) {
      const cat = match.matchedStockItem?.category?.trim() || (match.matchStatus === 'matched' ? '(Tanpa Kategori)' : '(Belum Cocok)');
      const existing = map.get(cat) || { count: 0, inStockCount: 0, items: [] };
      existing.count += 1;
      if (match.newStock !== null && match.newStock > 0) {
        existing.inStockCount += 1;
      }
      existing.items.push(match);
      map.set(cat, existing);
    }
    return Array.from(map.entries())
      .map(([name, data]) => ({
        name,
        count: data.count,
        inStockCount: data.inStockCount,
        items: data.items,
      }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  }, [matches]);

  // Extract unique Brands/Merks from matched items with count
  const brandStats = useMemo(() => {
    const map = new Map<string, { count: number; inStockCount: number; items: TokopediaRowMatch[] }>();
    for (const match of matches) {
      const brand = match.matchedStockItem?.brand?.trim() || (match.matchStatus === 'matched' ? '(Tanpa Merk)' : '(Belum Cocok)');
      const existing = map.get(brand) || { count: 0, inStockCount: 0, items: [] };
      existing.count += 1;
      if (match.newStock !== null && match.newStock > 0) {
        existing.inStockCount += 1;
      }
      existing.items.push(match);
      map.set(brand, existing);
    }
    return Array.from(map.entries())
      .map(([name, data]) => ({
        name,
        count: data.count,
        inStockCount: data.inStockCount,
        items: data.items,
      }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  }, [matches]);

  // Filtered categories in UI
  const filteredCategories = useMemo(() => {
    if (!categorySearch.trim()) return categoryStats;
    const q = categorySearch.toLowerCase().trim();
    return categoryStats.filter((c) =>
      c.name.toLowerCase().includes(q) ||
      c.items.some((it) => (it.skuCol4 || '').toLowerCase().includes(q) || (it.matchedStockItem?.code || '').toLowerCase().includes(q))
    );
  }, [categoryStats, categorySearch]);

  // Filtered brands in UI
  const filteredBrands = useMemo(() => {
    if (!brandSearch.trim()) return brandStats;
    const q = brandSearch.toLowerCase().trim();
    return brandStats.filter((b) =>
      b.name.toLowerCase().includes(q) ||
      b.items.some((it) => (it.skuCol4 || '').toLowerCase().includes(q) || (it.matchedStockItem?.code || '').toLowerCase().includes(q))
    );
  }, [brandStats, brandSearch]);

  // Items currently matching selected Category
  const itemsInSelectedCategories = useMemo(() => {
    if (selectedCategories.length === 0) return [];
    const set = new Set(selectedCategories);
    return matches.filter((it) => {
      const cat = it.matchedStockItem?.category?.trim() || (it.matchStatus === 'matched' ? '(Tanpa Kategori)' : '(Belum Cocok)');
      return set.has(cat);
    });
  }, [matches, selectedCategories]);

  // Items currently matching selected Brand
  const itemsInSelectedBrands = useMemo(() => {
    if (selectedBrands.length === 0) return [];
    const set = new Set(selectedBrands);
    return matches.filter((it) => {
      const brand = it.matchedStockItem?.brand?.trim() || (it.matchStatus === 'matched' ? '(Tanpa Merk)' : '(Belum Cocok)');
      return set.has(brand);
    });
  }, [matches, selectedBrands]);

  // Filtered individual items for Custom Checklist & Search
  const filteredItems = useMemo(() => {
    let result = matches;

    if (itemStockFilter === 'in_stock') {
      result = result.filter((it) => it.newStock !== null && it.newStock > 0);
    } else if (itemStockFilter === 'out_of_stock') {
      result = result.filter((it) => it.newStock !== null && it.newStock <= 0);
    }

    if (itemSearch.trim()) {
      const q = itemSearch.toLowerCase().trim();
      result = result.filter((it) => {
        const sku4 = (it.skuCol4 || '').toLowerCase();
        const stockCode = (it.matchedStockItem?.code || '').toLowerCase();
        const prodName = (it.productName || '').toLowerCase();
        const varName = (it.variationName || '').toLowerCase();
        const desc = (it.matchedStockItem?.description || '').toLowerCase();
        const cat = (it.matchedStockItem?.category || '').toLowerCase();
        const brand = (it.matchedStockItem?.brand || '').toLowerCase();
        return (
          sku4.includes(q) ||
          stockCode.includes(q) ||
          prodName.includes(q) ||
          varName.includes(q) ||
          desc.includes(q) ||
          cat.includes(q) ||
          brand.includes(q)
        );
      });
    }

    return result;
  }, [matches, itemSearch, itemStockFilter]);

  // Calculate total matching items to export based on selected mode
  const itemsToExportCount = useMemo(() => {
    if (mode === 'all') {
      return matches.length;
    }
    if (mode === 'category') {
      if (selectedCategories.length === 0) return 0;
      const set = new Set(selectedCategories);
      return matches.filter((it) => {
        const cat = it.matchedStockItem?.category?.trim() || (it.matchStatus === 'matched' ? '(Tanpa Kategori)' : '(Belum Cocok)');
        return set.has(cat);
      }).length;
    }
    if (mode === 'brand') {
      if (selectedBrands.length === 0) return 0;
      const set = new Set(selectedBrands);
      return matches.filter((it) => {
        const brand = it.matchedStockItem?.brand?.trim() || (it.matchStatus === 'matched' ? '(Tanpa Merk)' : '(Belum Cocok)');
        return set.has(brand);
      }).length;
    }
    if (mode === 'custom') {
      return selectedRowIndices.size;
    }
    return matches.length;
  }, [mode, selectedCategories, selectedBrands, selectedRowIndices, matches]);

  if (!isOpen) return null;

  const handleToggleCategory = (catName: string) => {
    setSelectedCategories((prev) =>
      prev.includes(catName) ? prev.filter((c) => c !== catName) : [...prev, catName]
    );
  };

  const handleSelectAllCategories = () => {
    setSelectedCategories(categoryStats.map((c) => c.name));
  };

  const handleDeselectAllCategories = () => {
    setSelectedCategories([]);
  };

  const handleToggleBrand = (brandName: string) => {
    setSelectedBrands((prev) =>
      prev.includes(brandName) ? prev.filter((b) => b !== brandName) : [...prev, brandName]
    );
  };

  const handleSelectAllBrands = () => {
    setSelectedBrands(brandStats.map((b) => b.name));
  };

  const handleDeselectAllBrands = () => {
    setSelectedBrands([]);
  };

  const handleToggleItem = (rowIndex: number) => {
    setSelectedRowIndices((prev) => {
      const next = new Set(prev);
      if (next.has(rowIndex)) {
        next.delete(rowIndex);
      } else {
        next.add(rowIndex);
      }
      return next;
    });
  };

  const handleSelectAllFilteredItems = () => {
    setSelectedRowIndices((prev) => {
      const next = new Set(prev);
      for (const it of filteredItems) {
        next.add(it.rowIndex);
      }
      return next;
    });
  };

  const handleDeselectAllFilteredItems = () => {
    setSelectedRowIndices((prev) => {
      const next = new Set(prev);
      for (const it of filteredItems) {
        next.delete(it.rowIndex);
      }
      return next;
    });
  };

  const handleConfirm = () => {
    onConfirmDownload(
      {
        mode,
        selectedCategories,
        selectedBrands,
        selectedRowIndices: Array.from(selectedRowIndices),
        storePrefix: customPrefix.trim() || effectiveBase,
      },
      dateFormat
    );
    onClose();
  };

  return (
    <div
      id="modal-tokopedia-download"
      className="fixed inset-0 z-50 overflow-y-auto bg-stone-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 animate-in fade-in duration-150"
    >
      <div className="bg-white rounded-2xl shadow-2xl border border-stone-200 w-full max-w-3xl overflow-hidden flex flex-col max-h-[92vh] animate-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-stone-200 flex items-center justify-between bg-stone-50/80 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-emerald-700 text-white flex items-center justify-center shadow-xs">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-stone-900 leading-tight flex items-center gap-2">
                <span>Pilih Format &amp; Filter Unduhan Tokopedia</span>
                <span className="text-[11px] font-bold text-emerald-800 bg-emerald-100 px-2 py-0.5 rounded-full border border-emerald-300">
                  Kolom 9 (Stok) Auto-Sync
                </span>
              </h2>
              <p className="text-xs text-stone-500">
                Filter produk berdasarkan Kategori atau Merk dari database <strong>{stockSheetName}</strong>. Nama file otomatis berubah sesuai pilihan Anda.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-stone-400 hover:text-stone-600 p-1.5 rounded-lg hover:bg-stone-200/60 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-4 sm:p-5 overflow-y-auto space-y-4 flex-1">
          {/* Mode Selection Cards */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-xs font-bold text-stone-700 uppercase tracking-wider">
                Pilih Ruang Lingkup Data (Mode Unduh):
              </label>
              <span className="text-[11px] text-emerald-800 font-medium bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-emerald-600" />
                {matches.filter((m) => m.matchStatus === 'matched').length} SKU Cocok
              </span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {/* Card 1: All */}
              <button
                type="button"
                onClick={() => setMode('all')}
                className={`p-3 rounded-xl border text-left flex flex-col justify-between transition-all cursor-pointer ${
                  mode === 'all'
                    ? 'bg-emerald-50/90 border-emerald-600 ring-2 ring-emerald-500/20 shadow-xs'
                    : 'bg-white border-stone-200 hover:bg-stone-50'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <Layers className={`w-4 h-4 ${mode === 'all' ? 'text-emerald-700' : 'text-stone-500'}`} />
                  <span
                    className={`text-[10px] font-bold px-1.5 py-0.2 rounded-full ${
                      mode === 'all' ? 'bg-emerald-200 text-emerald-900' : 'bg-stone-100 text-stone-600'
                    }`}
                  >
                    {matches.length}
                  </span>
                </div>
                <div>
                  <span className="text-xs font-bold text-stone-900 block">Semua Produk</span>
                  <span className="text-[11px] text-stone-500 block leading-tight">Seluruh baris file</span>
                </div>
              </button>

              {/* Card 2: By Category */}
              <button
                type="button"
                onClick={() => setMode('category')}
                className={`p-3 rounded-xl border text-left flex flex-col justify-between transition-all cursor-pointer ${
                  mode === 'category'
                    ? 'bg-emerald-50/90 border-emerald-600 ring-2 ring-emerald-500/20 shadow-xs'
                    : 'bg-white border-stone-200 hover:bg-stone-50'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <Tag className={`w-4 h-4 ${mode === 'category' ? 'text-emerald-700' : 'text-stone-500'}`} />
                  <span
                    className={`text-[10px] font-bold px-1.5 py-0.2 rounded-full ${
                      mode === 'category' ? 'bg-emerald-200 text-emerald-900' : 'bg-stone-100 text-stone-600'
                    }`}
                  >
                    {categoryStats.length} Kat
                  </span>
                </div>
                <div>
                  <span className="text-xs font-bold text-stone-900 block">Kategori</span>
                  <span className="text-[11px] text-stone-500 block leading-tight">Filter per Kategori</span>
                </div>
              </button>

              {/* Card 3: By Brand */}
              <button
                type="button"
                onClick={() => setMode('brand')}
                className={`p-3 rounded-xl border text-left flex flex-col justify-between transition-all cursor-pointer ${
                  mode === 'brand'
                    ? 'bg-emerald-50/90 border-emerald-600 ring-2 ring-emerald-500/20 shadow-xs'
                    : 'bg-white border-stone-200 hover:bg-stone-50'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <Briefcase className={`w-4 h-4 ${mode === 'brand' ? 'text-emerald-700' : 'text-stone-500'}`} />
                  <span
                    className={`text-[10px] font-bold px-1.5 py-0.2 rounded-full ${
                      mode === 'brand' ? 'bg-emerald-200 text-emerald-900' : 'bg-stone-100 text-stone-600'
                    }`}
                  >
                    {brandStats.length} Merk
                  </span>
                </div>
                <div>
                  <span className="text-xs font-bold text-stone-900 block">Merk / Brand</span>
                  <span className="text-[11px] text-stone-500 block leading-tight">DELI, Joyko, Pilot, dll</span>
                </div>
              </button>

              {/* Card 4: Custom Checklist */}
              <button
                type="button"
                onClick={() => setMode('custom')}
                className={`p-3 rounded-xl border text-left flex flex-col justify-between transition-all cursor-pointer ${
                  mode === 'custom'
                    ? 'bg-emerald-50/90 border-emerald-600 ring-2 ring-emerald-500/20 shadow-xs'
                    : 'bg-white border-stone-200 hover:bg-stone-50'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <CheckSquare className={`w-4 h-4 ${mode === 'custom' ? 'text-emerald-700' : 'text-stone-500'}`} />
                  <span
                    className={`text-[10px] font-bold px-1.5 py-0.2 rounded-full ${
                      mode === 'custom' ? 'bg-emerald-200 text-emerald-900' : 'bg-stone-100 text-stone-600'
                    }`}
                  >
                    {selectedRowIndices.size} SKU
                  </span>
                </div>
                <div>
                  <span className="text-xs font-bold text-stone-900 block">Checklist Sendiri</span>
                  <span className="text-[11px] text-stone-500 block leading-tight">Pilih manual per SKU</span>
                </div>
              </button>
            </div>
          </div>

          {/* DYNAMIC CONTENT PER MODE */}

          {/* MODE 1: ALL */}
          {mode === 'all' && (
            <div className="p-4 bg-stone-50 rounded-xl border border-stone-200 text-xs text-stone-700 space-y-2">
              <div className="flex items-center gap-2 text-stone-900 font-bold">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Seluruh {matches.length.toLocaleString('id-ID')} baris produk Tokopedia akan diunduh ke dalam file Excel.</span>
              </div>
              <p className="text-stone-500 leading-relaxed">
                Struktur kolom template Tokopedia (Kolom 4 = SKU, Kolom 9 = Stok) tetap terjaga rapi. Baris-baris data yang cocok dengan {stockSheetName} akan otomatis terisi nilai stok gudang terbaru.
              </p>
            </div>
          )}

          {/* MODE 2: CATEGORY FILTER */}
          {mode === 'category' && (
            <div className="space-y-3 p-4 bg-stone-50 rounded-xl border border-stone-200">
              <div className="p-2.5 bg-emerald-50/90 border border-emerald-200 rounded-lg flex items-start gap-2 text-xs text-emerald-900">
                <Sparkles className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold">Filter Kategori Berdasarkan Database {stockSheetName}: </span>
                  Kategori di bawah dipetakan langsung dari SKU Kolom 4 Tokopedia yang terhubung dengan database gudang. Memilih kategori akan menghasilkan file berisi produk kategori tersebut.
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Tag className="w-4 h-4 text-emerald-700" />
                  <span className="text-xs font-bold text-stone-900">
                    Pilih Kategori ({selectedCategories.length} dari {categoryStats.length} terpilih ➔ {itemsInSelectedCategories.length} Produk Siap Unduh)
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    onClick={handleSelectAllCategories}
                    className="text-[11px] font-semibold text-emerald-700 hover:text-emerald-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Pilih Semua
                  </button>
                  <button
                    type="button"
                    onClick={handleDeselectAllCategories}
                    className="text-[11px] font-semibold text-stone-600 hover:text-stone-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Hapus Pilihan
                  </button>
                </div>
              </div>

              {/* Search Bar for Category */}
              <div className="relative">
                <Search className="w-3.5 h-3.5 text-stone-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Cari nama kategori atau SKU..."
                  value={categorySearch}
                  onChange={(e) => setCategorySearch(e.target.value)}
                  className="w-full bg-white border border-stone-300 rounded-lg pl-8 pr-3 py-1.5 text-xs text-stone-800 placeholder-stone-400 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
              </div>

              {/* Category Checkbox Grid */}
              <div className="max-h-48 overflow-y-auto grid grid-cols-1 sm:grid-cols-2 gap-1.5 pr-1">
                {filteredCategories.length === 0 ? (
                  <div className="col-span-2 py-4 text-center text-xs text-stone-400">
                    Tidak ada kategori yang cocok dengan pencarian.
                  </div>
                ) : (
                  filteredCategories.map((cat) => {
                    const isChecked = selectedCategories.includes(cat.name);
                    return (
                      <label
                        key={cat.name}
                        onClick={() => handleToggleCategory(cat.name)}
                        className={`flex items-center justify-between p-2 rounded-lg border text-xs cursor-pointer transition-colors ${
                          isChecked
                            ? 'bg-emerald-50/90 border-emerald-400 text-emerald-950 font-semibold'
                            : 'bg-white border-stone-200 hover:bg-stone-100/70 text-stone-700'
                        }`}
                      >
                        <div className="flex items-center gap-2 truncate pr-2">
                          <input
                            type="checkbox"
                            checked={isChecked}
                            onChange={() => {}}
                            className="rounded text-emerald-600 focus:ring-emerald-500 shrink-0"
                          />
                          <span className="truncate">{cat.name}</span>
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <span className="text-[10px] font-mono font-medium px-1.5 py-0.2 rounded bg-stone-100 text-stone-600">
                            {cat.count} item
                          </span>
                          <span className="text-[10px] font-mono font-semibold px-1 py-0.2 rounded bg-emerald-100 text-emerald-800">
                            {cat.inStockCount} ready
                          </span>
                        </div>
                      </label>
                    );
                  })
                )}
              </div>

              {/* Live Preview of Matched SKUs under selected categories */}
              {selectedCategories.length > 0 && (
                <div className="pt-2 border-t border-stone-200">
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-[11px] font-bold text-stone-700">
                      Rincian Produk &amp; SKU yang Terpilih ({itemsInSelectedCategories.length} baris):
                    </span>
                    <button
                      type="button"
                      onClick={() => setShowItemPreview(!showItemPreview)}
                      className="text-[10px] font-semibold text-emerald-700 hover:underline cursor-pointer"
                    >
                      {showItemPreview ? 'Sembunyikan Daftar' : 'Tampilkan Daftar'}
                    </button>
                  </div>
                  {showItemPreview && (
                    <div className="max-h-36 overflow-y-auto border border-stone-200 rounded-lg bg-white divide-y divide-stone-100 text-xs">
                      {itemsInSelectedCategories.slice(0, 50).map((it) => (
                        <div key={it.rowIndex} className="p-1.5 px-2 flex items-center justify-between hover:bg-stone-50">
                          <div className="flex items-center gap-2 truncate pr-2">
                            <span className="font-mono font-bold text-emerald-900 bg-emerald-100 px-1.5 py-0.5 rounded text-[11px]">
                              {it.skuCol4 || it.matchedStockItem?.code || '-'}
                            </span>
                            <span className="truncate text-stone-800 text-[11px]">
                              {it.productName || it.matchedStockItem?.description || 'Tanpa Nama'}
                            </span>
                          </div>
                          <div className="shrink-0 text-right">
                            <span
                              className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded ${
                                it.newStock !== null && it.newStock > 0
                                  ? 'bg-emerald-50 text-emerald-700'
                                  : 'bg-rose-50 text-rose-700'
                              }`}
                            >
                              Stok: {it.newStock ?? it.originalStock}
                            </span>
                          </div>
                        </div>
                      ))}
                      {itemsInSelectedCategories.length > 50 && (
                        <div className="p-1.5 text-center text-[10px] text-stone-400 bg-stone-50">
                          ... dan {itemsInSelectedCategories.length - 50} produk lainnya
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* MODE 3: BRAND FILTER */}
          {mode === 'brand' && (
            <div className="space-y-3 p-4 bg-stone-50 rounded-xl border border-stone-200">
              <div className="p-2.5 bg-emerald-50/90 border border-emerald-200 rounded-lg flex items-start gap-2 text-xs text-emerald-900">
                <Sparkles className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold">Filter Merk / Brand Berdasarkan Database {stockSheetName}: </span>
                  Merk dipetakan dari pencocokan SKU Tokopedia dengan database gudang. Memilih merk (misalnya <strong>DELI</strong>) akan otomatis mengubah nama file unduhan menjadi <strong>DELI-tokopedia(23-09-2026).xlsx</strong>.
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-emerald-700" />
                  <span className="text-xs font-bold text-stone-900">
                    Pilih Merk / Brand ({selectedBrands.length} dari {brandStats.length} terpilih ➔ {itemsInSelectedBrands.length} Produk Siap Unduh)
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    onClick={handleSelectAllBrands}
                    className="text-[11px] font-semibold text-emerald-700 hover:text-emerald-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Pilih Semua
                  </button>
                  <button
                    type="button"
                    onClick={handleDeselectAllBrands}
                    className="text-[11px] font-semibold text-stone-600 hover:text-stone-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Hapus Pilihan
                  </button>
                </div>
              </div>

              {/* Search Bar for Brand */}
              <div className="relative">
                <Search className="w-3.5 h-3.5 text-stone-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Cari nama merk atau SKU (contoh: Deli, Joyko, Snowman)..."
                  value={brandSearch}
                  onChange={(e) => setBrandSearch(e.target.value)}
                  className="w-full bg-white border border-stone-300 rounded-lg pl-8 pr-3 py-1.5 text-xs text-stone-800 placeholder-stone-400 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
              </div>

              {/* Brand Checkbox Grid */}
              <div className="max-h-48 overflow-y-auto grid grid-cols-1 sm:grid-cols-2 gap-1.5 pr-1">
                {filteredBrands.length === 0 ? (
                  <div className="col-span-2 py-4 text-center text-xs text-stone-400">
                    Tidak ada merk yang cocok dengan pencarian.
                  </div>
                ) : (
                  filteredBrands.map((b) => {
                    const isChecked = selectedBrands.includes(b.name);
                    return (
                      <label
                        key={b.name}
                        onClick={() => handleToggleBrand(b.name)}
                        className={`flex items-center justify-between p-2 rounded-lg border text-xs cursor-pointer transition-colors ${
                          isChecked
                            ? 'bg-emerald-50/90 border-emerald-400 text-emerald-950 font-semibold'
                            : 'bg-white border-stone-200 hover:bg-stone-100/70 text-stone-700'
                        }`}
                      >
                        <div className="flex items-center gap-2 truncate pr-2">
                          <input
                            type="checkbox"
                            checked={isChecked}
                            onChange={() => {}}
                            className="rounded text-emerald-600 focus:ring-emerald-500 shrink-0"
                          />
                          <span className="truncate font-medium">{b.name}</span>
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <span className="text-[10px] font-mono font-medium px-1.5 py-0.2 rounded bg-stone-100 text-stone-600">
                            {b.count} item
                          </span>
                          <span className="text-[10px] font-mono font-semibold px-1 py-0.2 rounded bg-emerald-100 text-emerald-800">
                            {b.inStockCount} ready
                          </span>
                        </div>
                      </label>
                    );
                  })
                )}
              </div>

              {/* Live Preview of Matched SKUs under selected brands */}
              {selectedBrands.length > 0 && (
                <div className="pt-2 border-t border-stone-200">
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-[11px] font-bold text-stone-700">
                      Rincian Produk &amp; SKU yang Terpilih ({itemsInSelectedBrands.length} baris):
                    </span>
                    <button
                      type="button"
                      onClick={() => setShowItemPreview(!showItemPreview)}
                      className="text-[10px] font-semibold text-emerald-700 hover:underline cursor-pointer"
                    >
                      {showItemPreview ? 'Sembunyikan Daftar' : 'Tampilkan Daftar'}
                    </button>
                  </div>
                  {showItemPreview && (
                    <div className="max-h-36 overflow-y-auto border border-stone-200 rounded-lg bg-white divide-y divide-stone-100 text-xs">
                      {itemsInSelectedBrands.slice(0, 50).map((it) => (
                        <div key={it.rowIndex} className="p-1.5 px-2 flex items-center justify-between hover:bg-stone-50">
                          <div className="flex items-center gap-2 truncate pr-2">
                            <span className="font-mono font-bold text-emerald-900 bg-emerald-100 px-1.5 py-0.5 rounded text-[11px]">
                              {it.skuCol4 || it.matchedStockItem?.code || '-'}
                            </span>
                            <span className="truncate text-stone-800 text-[11px]">
                              {it.productName || it.matchedStockItem?.description || 'Tanpa Nama'}
                            </span>
                          </div>
                          <div className="shrink-0 text-right">
                            <span
                              className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded ${
                                it.newStock !== null && it.newStock > 0
                                  ? 'bg-emerald-50 text-emerald-700'
                                  : 'bg-rose-50 text-rose-700'
                              }`}
                            >
                              Stok: {it.newStock ?? it.originalStock}
                            </span>
                          </div>
                        </div>
                      ))}
                      {itemsInSelectedBrands.length > 50 && (
                        <div className="p-1.5 text-center text-[10px] text-stone-400 bg-stone-50">
                          ... dan {itemsInSelectedBrands.length - 50} produk lainnya
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* MODE 4: CUSTOM CHECKLIST */}
          {mode === 'custom' && (
            <div className="space-y-3 p-4 bg-stone-50 rounded-xl border border-stone-200">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <CheckSquare className="w-4 h-4 text-emerald-700" />
                  <span className="text-xs font-bold text-stone-900">
                    Checklist Mandiri ({selectedRowIndices.size} dari {matches.length} SKU terpilih)
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    onClick={handleSelectAllFilteredItems}
                    className="text-[11px] font-semibold text-emerald-700 hover:text-emerald-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Pilih Yang Tampil ({filteredItems.length})
                  </button>
                  <button
                    type="button"
                    onClick={handleDeselectAllFilteredItems}
                    className="text-[11px] font-semibold text-stone-600 hover:text-stone-900 bg-white px-2.5 py-1 rounded-md border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
                  >
                    Batal Pilih
                  </button>
                </div>
              </div>

              {/* Search & Stock Filter */}
              <div className="flex flex-col sm:flex-row gap-2">
                <div className="relative flex-1">
                  <Search className="w-3.5 h-3.5 text-stone-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
                  <input
                    type="text"
                    placeholder="Cari SKU Tokopedia, Nama Produk, Kategori, Merk..."
                    value={itemSearch}
                    onChange={(e) => setItemSearch(e.target.value)}
                    className="w-full bg-white border border-stone-300 rounded-lg pl-8 pr-3 py-1.5 text-xs text-stone-800 placeholder-stone-400 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                  />
                </div>
                <div className="flex items-center gap-1 shrink-0 bg-white p-0.5 rounded-lg border border-stone-300 text-xs">
                  <button
                    type="button"
                    onClick={() => setItemStockFilter('all')}
                    className={`px-2 py-1 rounded text-[11px] font-medium transition-colors ${
                      itemStockFilter === 'all' ? 'bg-stone-800 text-white' : 'text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    Semua
                  </button>
                  <button
                    type="button"
                    onClick={() => setItemStockFilter('in_stock')}
                    className={`px-2 py-1 rounded text-[11px] font-medium transition-colors ${
                      itemStockFilter === 'in_stock' ? 'bg-emerald-600 text-white' : 'text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    Stok &gt; 0
                  </button>
                  <button
                    type="button"
                    onClick={() => setItemStockFilter('out_of_stock')}
                    className={`px-2 py-1 rounded text-[11px] font-medium transition-colors ${
                      itemStockFilter === 'out_of_stock' ? 'bg-rose-600 text-white' : 'text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    Stok 0 / Kosong
                  </button>
                </div>
              </div>

              {/* Item List Table */}
              <div className="max-h-60 overflow-y-auto border border-stone-200 rounded-lg bg-white divide-y divide-stone-100">
                {filteredItems.length === 0 ? (
                  <div className="py-6 text-center text-xs text-stone-400">
                    Tidak ada produk yang cocok dengan kriteria pencarian.
                  </div>
                ) : (
                  filteredItems.map((item) => {
                    const isSelected = selectedRowIndices.has(item.rowIndex);
                    const skuDisplay = item.skuCol4 || `Baris #${item.displayRow}`;
                    const name = item.productName || item.matchedStockItem?.description || '-';
                    const cat = item.matchedStockItem?.category || '';
                    const brand = item.matchedStockItem?.brand || '';

                    return (
                      <div
                        key={item.rowIndex}
                        onClick={() => handleToggleItem(item.rowIndex)}
                        className={`p-2.5 flex items-center justify-between text-xs cursor-pointer transition-colors ${
                          isSelected ? 'bg-emerald-50/50 hover:bg-emerald-50' : 'hover:bg-stone-50'
                        }`}
                      >
                        <div className="flex items-center gap-2.5 min-w-0 pr-2">
                          <input
                            type="checkbox"
                            checked={isSelected}
                            onChange={() => {}}
                            className="rounded text-emerald-600 focus:ring-emerald-500 shrink-0"
                          />
                          <div className="min-w-0">
                            <div className="flex items-center gap-1.5 flex-wrap">
                              <span className="font-mono font-bold text-stone-900 text-xs bg-stone-100 px-1.5 py-0.5 rounded">
                                {skuDisplay}
                              </span>
                              {brand && (
                                <span className="text-[10px] bg-purple-50 text-purple-800 border border-purple-200 px-1.5 py-0.2 rounded">
                                  {brand}
                                </span>
                              )}
                              {cat && (
                                <span className="text-[10px] bg-sky-50 text-sky-800 border border-sky-200 px-1.5 py-0.2 rounded">
                                  {cat}
                                </span>
                              )}
                            </div>
                            <p className="text-stone-600 truncate text-[11px] mt-0.5">{name}</p>
                          </div>
                        </div>

                        <div className="text-right shrink-0">
                          {item.newStock !== null ? (
                            <span
                              className={`text-xs font-mono font-bold px-2 py-0.5 rounded-full ${
                                item.newStock > 0
                                  ? 'bg-emerald-100 text-emerald-800'
                                  : 'bg-rose-100 text-rose-800'
                              }`}
                            >
                              Stok: {item.newStock}
                            </span>
                          ) : (
                            <span className="text-[10px] bg-stone-100 text-stone-500 px-1.5 py-0.5 rounded">
                              Stok Asli: {item.originalStock}
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          )}

          {/* Export Settings: Prefix & Summary */}
          <div className="p-3.5 bg-stone-50 rounded-xl border border-stone-200 space-y-2.5">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
              <div>
                <label className="block text-xs font-bold text-stone-800 flex items-center gap-1.5 flex-wrap">
                  <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-700" />
                  <span>Nama Prefix File Toko:</span>
                  {mode === 'brand' && selectedBrands.length > 0 && (
                    <span className="text-[10px] font-bold text-emerald-900 bg-emerald-100 border border-emerald-300 px-1.5 py-0.2 rounded-md">
                      Merk: {selectedBrands.join(', ')}
                    </span>
                  )}
                  {mode === 'category' && selectedCategories.length > 0 && (
                    <span className="text-[10px] font-bold text-sky-900 bg-sky-100 border border-sky-300 px-1.5 py-0.2 rounded-md">
                      Kategori: {selectedCategories.join(', ')}
                    </span>
                  )}
                </label>
                <p className="text-[11px] text-stone-500 mt-0.5">
                  Nama file otomatis menyesuaikan filter (contoh: <strong className="text-stone-700 font-mono">DELI-tokopedia</strong>), atau ketik custom nama sesuai keinginan Anda.
                </p>
              </div>

              <div className="flex items-center gap-2">
                <input
                  type="text"
                  id="input-custom-prefix-tokopedia"
                  value={customPrefix}
                  onChange={(e) => setCustomPrefix(e.target.value.replace(/[^a-zA-Z0-9_.-]/g, ''))}
                  placeholder={autoGeneratedPrefix || 'tokopedia'}
                  className="w-40 sm:w-48 bg-white border border-stone-300 rounded-lg px-2.5 py-1.5 text-xs font-mono font-bold text-stone-900 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 text-center shadow-2xs"
                />
                {customPrefix !== autoGeneratedPrefix && (
                  <button
                    type="button"
                    onClick={() => setCustomPrefix(autoGeneratedPrefix)}
                    className="text-[11px] font-semibold text-emerald-700 hover:text-emerald-900 hover:underline cursor-pointer shrink-0"
                    title="Kembalikan ke nama otomatis sesuai filter yang dicentang"
                  >
                    Reset Auto
                  </button>
                )}
              </div>
            </div>

            {/* Format Date Selector & Live Filename Preview */}
            <div className="pt-2 border-t border-stone-200/80 flex flex-wrap items-center justify-between gap-2 text-[11px]">
              <div className="flex items-center gap-2">
                <span className="text-stone-500 flex items-center gap-1 font-medium">
                  <Calendar className="w-3.5 h-3.5 text-stone-400" />
                  Format Tanggal:
                </span>
                <div className="flex items-center gap-1 bg-white p-0.5 rounded-md border border-stone-300 text-[10px]">
                  <button
                    type="button"
                    onClick={() => setDateFormat('dash')}
                    className={`px-2 py-0.5 rounded font-medium transition-colors ${
                      dateFormat === 'dash' ? 'bg-emerald-700 text-white' : 'text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    (DD-MM-YYYY)
                  </button>
                  <button
                    type="button"
                    onClick={() => setDateFormat('readable')}
                    className={`px-2 py-0.5 rounded font-medium transition-colors ${
                      dateFormat === 'readable' ? 'bg-emerald-700 text-white' : 'text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    (Tgl Bulan Jam)
                  </button>
                </div>
              </div>

              <div className="flex items-center gap-1.5">
                <span className="text-stone-500 font-medium">Pratinjau File:</span>
                <span className="font-mono font-bold text-emerald-900 bg-emerald-50 px-2.5 py-1 rounded-md border border-emerald-200 text-xs">
                  {generateTokopediaFilename(customPrefix.trim() || autoGeneratedPrefix, new Date(), dateFormat)}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 sm:p-5 border-t border-stone-200 bg-stone-50/80 flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
          <div className="text-xs text-stone-600 flex items-center gap-1.5">
            <span className="font-medium">Total Produk Siap Unduh:</span>
            <span className="font-bold text-emerald-700 text-sm font-mono bg-emerald-100/80 px-2 py-0.5 rounded-md">
              {itemsToExportCount} Produk
            </span>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 sm:flex-none px-4 py-2 text-xs font-semibold text-stone-700 bg-white border border-stone-300 rounded-xl hover:bg-stone-100 transition-colors cursor-pointer"
            >
              Batal
            </button>
            <button
              type="button"
              onClick={handleConfirm}
              disabled={itemsToExportCount === 0 || isProcessing}
              className="flex-1 sm:flex-none px-5 py-2 text-xs font-bold text-white bg-emerald-700 hover:bg-emerald-800 disabled:bg-stone-300 disabled:cursor-not-allowed rounded-xl shadow-xs transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Unduh File Tokopedia ({itemsToExportCount})</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
